export const ApplicationStatus = {
    PAUSED: 'PAUSED',
    PLAYING: 'PLAYING',
};

export const ActionTypes = {
    DECREMENT_OPERATION: 'DECREMENT_OPERATION',
    INCREMENT_OPERATION: 'INCREMENT_OPERATION',
    GO_TO_FIRST_OPERATION: 'GO_TO_FIRST_OPERATION',
    GO_TO_LAST_OPERATION: 'GO_TO_LAST_OPERATION',
    APPLICATION_PLAY: 'APPLICATION_PLAY',
    APPLICATION_PAUSE: 'APPLICATION_PAUSE',
    PROCESS_OPERATION: 'DO_OPERATION',
};

export const OperationTypes = {
    COMPARE: 'COMPARE',
    SWAP: 'SWAP',
};

export const IntervalTypes = {
    PROCESS_OPERATIONS: 'PROCESS_OPERATIONS'
}